/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: DinoJump
@author: LinuxDino
@tags: []
@addedOn: 2024-00-00
@GitHub: https://github.com/LinuxDinoGitHub/DinoJumpSprig
*/

const player = "p"
const display = 'd'

setLegend(
  [display, bitmap`
.........0000...
.......00DDD00..
.......0DDD0D0..
......0DDDDDDD0.
......0DDDDD220.
......0DDD0000..
......0DDDD90...
.....00DDDDC0...
....04DDDDD9000.
...04DDDDDDC0...
..04DDDDDDD000..
.00000000000....
....0....0......
....0....0......
....00...00.....
................`],
  [player, bitmap`
................
................
................
................
................
................
................
................
.......DDD......
.......DDDD.....
.......DDD0.....
.......DDD9.....
......DDDDC.....
.....DDD0D9.....
.....0..0.......
................`],
)

setSolids([])

let level = 0
const levels = [
  map`
p.
..`
]

setMap(levels[level])

setPushables({
  [player]: []
})

onInput("s", () => {
  getFirst(player).y += 1
})

afterInput(() => {

})